/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_codepath_examples_audiovideodemo_hellotest */

#ifndef _Included_com_codepath_examples_audiovideodemo_hellotest
#define _Included_com_codepath_examples_audiovideodemo_hellotest
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_codepath_examples_audiovideodemo_hellotest
 * Method:    nativeDataPush
 * Signature: ([BI)J
 */
JNIEXPORT jlong JNICALL Java_com_codepath_examples_audiovideodemo_hellotest_nativeDataPush
  (JNIEnv *, jclass, jbyteArray, jint);

/*
 * Class:     com_codepath_examples_audiovideodemo_hellotest
 * Method:    nativePicDataPush
 * Signature: ([BI)J
 */
JNIEXPORT jlong JNICALL Java_com_codepath_examples_audiovideodemo_hellotest_nativePicDataPush
  (JNIEnv *, jclass, jbyteArray, jint);

/*
 * Class:     com_codepath_examples_audiovideodemo_hellotest
 * Method:    nativeVideoParameters
 * Signature: (III)J
 */
JNIEXPORT jlong JNICALL Java_com_codepath_examples_audiovideodemo_hellotest_nativeVideoParameters
  (JNIEnv *, jclass, jint, jint, jint);

/*
 * Class:     com_codepath_examples_audiovideodemo_hellotest
 * Method:    nativeAudioParameters
 * Signature: (III)J
 */
JNIEXPORT jlong JNICALL Java_com_codepath_examples_audiovideodemo_hellotest_nativeAudioParameters
  (JNIEnv *, jclass, jint, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
